### ISSUE TITLE
Testing in enzyme creates TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by mschipperheyn** [APSL/react-native-keyboard-aware-scroll-view#320]
When mounting a component that contains `KeyboardAwareScrollView`, it generates an error 

```
 TypeError: Cannot read property 'displayName' of undefined

      at getDisplayName (node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js:58:27)
      at KeyboardAwareHOC (node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js:415:103)
      at listenToKeyboardEvents (node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js:448:12)
      at Object.<anonymous> (node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareSectionList.js:12:46)
      at Object.<anonymous> (node_modules/react-native-keyboard-aware-scroll-view/index.js:45:56)

```

This might occur bc I use a `React.Fragment` as a child of `KeyboardAwareScrollView`

**Comment by dkadlecek** [comment]
This error can be fixed by changing this code in KeyboardAwareHOC.js (106):

function getDisplayName(WrappedComponent: React$Component) {
  return WrappedComponent && (WrappedComponent.displayName || WrappedComponent.name) || 'Component'
}

I'll put together a PR shortly.

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.8.0
